### PR TITLE
Fixed the validation code for fields with IBAN masks

### PR DESCRIPTION
**Pull request by slimndap**
Code wasn't really checking if the field value is empty and was trying to validate empty strings.

### CODE REVIEW

**Comment by SieBer15** [comment]
Is it possible to make this add-on only validate visible fields?
It does not send now if it is hidden.

See example at http://sieber.nl/test/gravity/

When I choose iDeal in my testform it wil not send, because IBAN is not filled out.

**Comment by slimndap** [comment]
Isn't this automatically handled by Gravity Forms? Just make you use conditional logic to hide the IBAN field when it is not required.

**Comment by SieBer15** [comment]
No it is not handled automatically.

You can try my example at http://sieber.nl/test/gravity/

Login at http://sieber.nl/test/gravity/inloggen
Username: GravityForms
Password: Testing

**Comment by slimndap** [comment]
I think it's best to [open a new issue](https://github.com/AdmiumNL/adm-gravity-iban/issues/new) for this, since it not related to the issue of this page. Maybe the author of the plugin will pick it up.

If not, then you can [contact me](mailto:jeroen@slimndap.com) directly for a fix.

**Comment by SieBer15** [comment]
Thanks! I already made it a new issue. 
If he not picks it up, are you able to fix this and what are your costs?

**Pull request merged**
